# Generated by Django 4.2.3 on 2023-08-17 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0004_alter_country_name_alter_municipality_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(max_length=50, verbose_name='primer nombre')),
                ('second_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='segundo nombre')),
                ('first_surname', models.CharField(max_length=50, verbose_name='primer apellido')),
                ('second_surname', models.CharField(blank=True, max_length=50, null=True, verbose_name='segundo apellido')),
                ('birthday_date', models.DateField(verbose_name='fecha de nacimiento')),
                ('identity_card', models.CharField(blank=True, max_length=10, null=True, verbose_name='cedula de identidad')),
                ('gender', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='students', to='common.gender')),
            ],
            options={
                'verbose_name': 'estudiante',
                'verbose_name_plural': 'estudiantes',
            },
        ),
        migrations.CreateModel(
            name='Representative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(max_length=50, verbose_name='primer nombre')),
                ('second_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='segundo nombre')),
                ('first_surname', models.CharField(max_length=50, verbose_name='primer apellido')),
                ('second_surname', models.CharField(blank=True, max_length=50, null=True, verbose_name='segundo apellido')),
                ('identity_card', models.CharField(max_length=10, verbose_name='cedula de identidad')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='correo electronico')),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True, verbose_name='numero de telefono')),
                ('address', models.CharField(max_length=200, verbose_name='direccion')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='representatives', to='students.student', verbose_name='estudiante')),
            ],
            options={
                'verbose_name': 'representante',
                'verbose_name_plural': 'representantes',
            },
        ),
        migrations.CreateModel(
            name='AdditionalStudentData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('size', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True, verbose_name='talla')),
                ('weight', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, verbose_name='peso')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='correo electronico')),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True, verbose_name='numero de telefono')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_data', to='students.student', verbose_name='estudiante')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
