# Generated by Django 4.2.3 on 2023-10-30 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='representative',
            name='address',
            field=models.CharField(max_length=200, null=True, verbose_name='direccion'),
        ),
    ]
