# Generated by Django 4.2.3 on 2023-10-30 18:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_alter_representative_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additionalstudentdata',
            name='student',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='students.student', verbose_name='estudiante'),
        ),
        migrations.AlterField(
            model_name='representative',
            name='student',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='students.student', verbose_name='estudiante'),
        ),
    ]
