# Generated by Django 4.2.3 on 2023-11-07 16:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_shift'),
        ('students', '0003_alter_additionalstudentdata_student_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='gender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='students', to='common.gender', verbose_name='genero'),
        ),
    ]
