# Generated by Django 4.2.3 on 2023-11-08 01:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_alter_student_gender'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='additionalstudentdata',
            options={'verbose_name': 'informacion adicional del estudiante', 'verbose_name_plural': 'informacion adicional de los estudiantes'},
        ),
        migrations.RemoveField(
            model_name='representative',
            name='student',
        ),
        migrations.AddField(
            model_name='student',
            name='representative',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='students', to='students.representative', verbose_name='representante'),
        ),
    ]
