# Generated by Django 4.2.3 on 2023-08-07 20:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_contries_created_at_contries_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='States',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contry_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='common.contries')),
            ],
        ),
    ]
