# Generated by Django 4.2.3 on 2023-08-07 20:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_states'),
    ]

    operations = [
        migrations.CreateModel(
            name='Municipalities',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('state_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='common.states')),
            ],
        ),
        migrations.CreateModel(
            name='Parishes',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('Municipality_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='common.municipalities')),
            ],
        ),
    ]
