# Generated by Django 4.2.3 on 2023-11-06 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_alter_country_name_alter_municipality_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turn', models.CharField(max_length=20, verbose_name='turno')),
            ],
            options={
                'verbose_name': 'jornada de estudio',
                'verbose_name_plural': 'jornadas de estudio',
            },
        ),
    ]
