# Generated by Django 4.2.3 on 2024-01-17 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_shift'),
    ]

    operations = [
        migrations.CreateModel(
            name='Moment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=3, verbose_name='numero de momento')),
            ],
            options={
                'verbose_name': 'momento',
                'verbose_name_plural': 'momentos',
            },
        ),
    ]
