# Generated by Django 4.2.3 on 2024-01-18 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0007_alter_country_options_alter_municipality_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={'verbose_name': 'pais', 'verbose_name_plural': 'paises'},
        ),
        migrations.AlterModelOptions(
            name='municipality',
            options={'verbose_name': 'municipio', 'verbose_name_plural': 'municipios'},
        ),
        migrations.AlterModelOptions(
            name='state',
            options={'verbose_name': 'estado', 'verbose_name_plural': 'estados'},
        ),
    ]
