# Generated by Django 4.2.3 on 2024-04-21 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0009_audit'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Audit',
        ),
    ]
