# Generated by Django 4.2.3 on 2023-08-17 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50, verbose_name='nombre')),
            ],
            options={
                'verbose_name': 'materia',
                'verbose_name_plural': 'materias',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(max_length=50, verbose_name='primer nombre')),
                ('second_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='segundo nombre')),
                ('first_surname', models.CharField(max_length=50, verbose_name='primer apellido')),
                ('second_surname', models.CharField(blank=True, max_length=50, null=True, verbose_name='segundo apellido')),
                ('identity_card', models.CharField(max_length=10, verbose_name='cedula de identidad')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='correo electronico')),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True, verbose_name='numero de telefono')),
                ('address', models.CharField(max_length=200, verbose_name='direccion')),
            ],
            options={
                'verbose_name': 'docente',
                'verbose_name_plural': 'docentes',
            },
        ),
    ]
