# Generated by Django 4.2.3 on 2023-10-30 23:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academic_data', '0004_grade_sections'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='grade',
            options={'ordering': ['year'], 'verbose_name': 'grado', 'verbose_name_plural': 'grados'},
        ),
        migrations.AlterModelOptions(
            name='section',
            options={'ordering': ['group'], 'verbose_name': 'seccion', 'verbose_name_plural': 'secciones'},
        ),
        migrations.AlterModelOptions(
            name='subject',
            options={'ordering': ['name'], 'verbose_name': 'materia', 'verbose_name_plural': 'materias'},
        ),
    ]
