# Generated by Django 4.2.3 on 2023-11-06 12:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_alter_country_name_alter_municipality_name_and_more'),
        ('academic_data', '0005_alter_grade_options_alter_section_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='parish',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.parish', verbose_name='parroquia'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='subjects',
            field=models.ManyToManyField(related_name='materias', to='academic_data.subject'),
        ),
    ]
