# Generated by Django 4.2.3 on 2023-11-06 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_alter_country_name_alter_municipality_name_and_more'),
        ('academic_data', '0006_teacher_parish_teacher_subjects'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='gender',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='teachers', to='common.gender', verbose_name='genero'),
        ),
    ]
