# Generated by Django 4.2.3 on 2023-11-06 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic_data', '0007_teacher_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='subjects',
            field=models.ManyToManyField(to='academic_data.subject', verbose_name='materias'),
        ),
    ]
