# Generated by Django 4.2.3 on 2023-11-06 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic_data', '0008_alter_teacher_subjects'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='birthday_date',
            field=models.DateField(null=True, verbose_name='fecha de nacimiento'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='start_date',
            field=models.DateField(null=True, verbose_name='fecha de inicio'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='status',
            field=models.CharField(choices=[('active', 'activo'), ('inactive', 'inactivo')], default='active', max_length=10, verbose_name='estatus'),
        ),
    ]
