# Generated by Django 4.2.3 on 2023-11-06 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academic_data', '0009_teacher_birthday_date_teacher_start_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grade',
            name='sections',
        ),
    ]
