# Generated by Django 4.2.3 on 2023-11-06 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic_data', '0012_alter_section_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='year',
            field=models.CharField(max_length=3, unique=True, verbose_name='año'),
        ),
        migrations.AlterField(
            model_name='section',
            name='group',
            field=models.CharField(max_length=1, unique=True, verbose_name='grupo'),
        ),
    ]
