# Generated by Django 4.2.3 on 2023-11-07 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic_data', '0013_alter_grade_year_alter_section_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='identity_card',
            field=models.CharField(max_length=10, unique=True, verbose_name='cedula de identidad'),
        ),
    ]
