# Generated by Django 4.2.3 on 2023-11-24 01:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_shift'),
        ('students', '0005_alter_additionalstudentdata_options_and_more'),
        ('academic_data', '0015_academicperiod_delete_sectiongradeshift'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tuition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic_data.academicperiod', verbose_name='periodo academico')),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic_data.grade', verbose_name='grado')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic_data.section', verbose_name='seccion')),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.shift', verbose_name='turno')),
                ('students', models.ManyToManyField(to='students.student', verbose_name='estudiantes')),
            ],
            options={
                'verbose_name': 'matricula',
                'verbose_name_plural': 'matriculas',
                'default_related_name': 'tuitions',
            },
        ),
    ]
