# Generated by Django 4.2.3 on 2023-11-24 01:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_shift'),
        ('academic_data', '0016_tuition'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tuition',
            unique_together={('academic_period', 'grade', 'section', 'shift')},
        ),
    ]
