# Generated by Django 4.2.3 on 2023-11-24 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academic_data', '0017_alter_tuition_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tuition',
            unique_together={('academic_period', 'grade', 'section')},
        ),
    ]
