# Generated by Django 4.2.3 on 2023-11-27 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_alter_additionalstudentdata_options_and_more'),
        ('academic_data', '0018_alter_tuition_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tuition',
            name='students',
            field=models.ManyToManyField(blank=True, to='students.student', verbose_name='estudiantes'),
        ),
    ]
