# Generated by Django 4.2.3 on 2024-01-10 21:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_alter_additionalstudentdata_options_and_more'),
        ('academic_data', '0019_alter_tuition_students'),
    ]

    operations = [
        migrations.CreateModel(
            name='Qualification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('note', models.DecimalField(decimal_places=1, max_digits=3, verbose_name='nota')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student', verbose_name='estudiante')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic_data.subject', verbose_name='materia')),
                ('tuition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic_data.tuition', verbose_name='matricula')),
            ],
            options={
                'verbose_name': 'calificacion',
                'verbose_name_plural': 'calificaciones',
                'default_related_name': 'qualifications',
            },
        ),
    ]
