# Generated by Django 4.2.3 on 2024-01-18 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic_data', '0021_qualification_moment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='subjects',
            field=models.ManyToManyField(null=True, to='academic_data.subject', verbose_name='materias'),
        ),
    ]
