# Generated by Django 4.2.3 on 2024-02-14 22:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("academic_data", "0022_alter_teacher_subjects"),
    ]

    operations = [
        migrations.AlterField(
            model_name="teacher",
            name="subjects",
            field=models.ManyToManyField(
                to="academic_data.subject", verbose_name="materias"
            ),
        ),
    ]
