# Generated by Django 4.2.3 on 2024-02-15 01:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("academic_data", "0023_alter_teacher_subjects"),
    ]

    operations = [
        migrations.AlterField(
            model_name="qualification",
            name="note",
            field=models.DecimalField(
                decimal_places=1, default=0.0, max_digits=3, verbose_name="nota"
            ),
        ),
    ]
