# Generated by Django 4.2.3 on 2024-02-23 03:01

from django.db import migrations

CREATE_SQL = """ 
    CREATE OR REPLACE VIEW public.academic_notes_all
    AS
    SELECT DISTINCT stu.id AS student_id,
        aca.id AS matricula,
        stu.first_name AS p_nombre,
        stu.second_name AS s_nombre,
        stu.first_surname AS p_apellido,
        stu.second_surname AS s_apellido,
        stu.identity_card AS cedula,
        gra.year AS grado,
        sec."group" AS seccion,
        tur.turn AS turno,
        mon.number AS lapso,
        per.period,
        sub.name AS asignacion,
            CASE
                WHEN qua.note IS NOT NULL AND qua.student_id = stu.id THEN qua.note
                ELSE NULL::numeric
            END AS nota
    FROM academic_data_tuition_students ate,
        common_shift tur,
        academic_data_academicperiod per,
        academic_data_section sec,
        academic_data_tuition aca,
        academic_data_grade gra,
        students_student stu
        LEFT JOIN academic_data_subject sub ON 1 = 1
        LEFT JOIN academic_data_qualification qua ON sub.id = qua.subject_id AND qua.student_id = stu.id
        LEFT JOIN common_moment mon ON qua.moment_id = mon.id
    WHERE aca.grade_id = gra.id AND sec.id = aca.section_id AND per.id = aca.academic_period_id AND tur.id = aca.shift_id AND ate.student_id = stu.id AND ate.tuition_id = aca.id;

    ALTER TABLE public.academic_notes_all
        OWNER TO postgres;
"""

DROP_SQL = "public.academic_notes_all"

class Migration(migrations.Migration):
    dependencies = [
        ("academic_data", "0025_grade_subjects"),
    ]

    operations = [
        migrations.RunSQL(
            sql=CREATE_SQL,
            reverse_sql=DROP_SQL,
        ),
    ]
