# Generated by Django 4.2.3 on 2024-02-23 03:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("academic_data", "0026_auto1_20240222_2301"),
    ]

    operations = [
        migrations.CreateModel(
            name="AllNotes",
            fields=[
                (
                    "student_id",
                    models.IntegerField(
                        primary_key=True, serialize=False, verbose_name="estudiante"
                    ),
                ),
                ("matricula", models.IntegerField(verbose_name="matricula")),
                ("cedula", models.CharField(max_length=50, verbose_name="cedula")),
                ("p_nombre", models.CharField(max_length=50, verbose_name="p_nombre")),
                ("s_nombre", models.CharField(max_length=50, verbose_name="s_nombre")),
                (
                    "p_apellido",
                    models.CharField(max_length=50, verbose_name="p_apellido"),
                ),
                (
                    "s_apellido",
                    models.CharField(max_length=50, verbose_name="s_apellido"),
                ),
                ("grado", models.CharField(max_length=50, verbose_name="grado")),
                ("seccion", models.CharField(max_length=50, verbose_name="seccion")),
                ("turno", models.CharField(max_length=50, verbose_name="turno")),
                ("lapso", models.CharField(max_length=50, verbose_name="lapso")),
                (
                    "asignacion",
                    models.CharField(max_length=50, verbose_name="asignacion"),
                ),
                ("nota", models.CharField(max_length=50, verbose_name="nota")),
            ],
            options={
                "db_table": "academic_notes_all",
                "managed": False,
            },
        ),
    ]
