# Generated by Django 4.2.3 on 2024-04-21 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academic_data', '0028_academicperiod_is_deleted_grade_is_deleted_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='academicperiod',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='grade',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='qualification',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='section',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='tuition',
            name='is_deleted',
        ),
    ]
