# Generated by Django 4.2.3 on 2024-04-21 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='audit',
            name='description',
            field=models.CharField(default=None, max_length=100, verbose_name='descripcion'),
        ),
    ]
