# Generated by Django 4.2.3 on 2024-04-21 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0002_audit_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='audit',
            options={'ordering': ['-id'], 'verbose_name_plural': 'auditoria'},
        ),
    ]
